# Code based on: https://medium.com/@VeselyCodes/bi-weekly-github-actions-7bea6be7bd96

name: Bi-weekly Slack Poll

on:
  schedule:
    # Runs at 7:00 AM UTC (9:00 Turku) every two Wednesdays
    - cron: '0 7 * * 3'
  workflow_dispatch:

env:
  # The date of the first run of the action. It has to be set to a date that is on the same weekday as the cron.
  # 12/11 is Monday, so the cron is set to run on Monday.
  # Every second week of the bi-weekly cycle, the action is going to be skipped.
  # The cron time can be set to any time of the day.
  FIRST_RUN_DATE: 2024-02-19
jobs:
  weekindex:
    runs-on: ubuntu-latest
    outputs:
      weekindex: ${{ steps.calculate.outputs.weekindex }}
    steps:
      - name: Calculate weekdiff
        id: calculate
        run: |
          current_date=$(date +%Y-%m-%d)
          start=$(date -d ${{ env.FIRST_RUN_DATE }} +%s)
          end=$(date -d $current_date +%s)
          weekdiff=$(((end-start) / 60 / 60 / 24 / 7))
          weekindex=$((weekdiff % 2))
          echo "weekindex=$weekindex" >> "$GITHUB_OUTPUT"
  
  action:
    if: ${{ needs.weekindex.outputs.weekindex == 0 }}  
    runs-on: ubuntu-latest
    needs:
      - weekindex
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Send a Slack reminder to udpate the labmeeting slides
        env:
            SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
            SLACK_CHANNEL: ${{ secrets.SLACK_LUNCH_CHANNEL }}
        run: |
            python scripts/biweekly_lunch_poll.py --token $SLACK_TOKEN --channel $SLACK_CHANNEL
